apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: cat
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
    image: kind/healthcheck:a42e6a21d79986a18bd89a98ec608e007a1a3948492596e0530466635157e6d6
  image: kind/challenge:ff2d5d789efe7a6c6f8f45da9850bf12520ca370aa744f0b8e3a6ded1fad9d2a
