apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: squirrel-feeding
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: true
    image: kind/healthcheck:764c544f80b6884712ddaedb364b1c2cc7f88153d8c28be1f9e09f79de6e3713
  image: kind/challenge:aea3359bcf4c9d4f49418412d1206168d2da71fb7214357a963d2d023b799ad3
